model = nn.Sequential()
model:add( nn.SpatialConvolutionMM(1,20,5,5) )
model:add( nn.ReLU() )
model:add( nn.SpatialMaxPooling(2,2,2,2))
model:add( nn.SpatialConvolution(20,40,5,5) )
model:add( nn.ReLU() )
model:add( nn.SpatialMaxPooling(2,2,2,2))
model:add( nn.Reshape(40*4*4) )
model:add( nn.Linear(40*4*4,200) )
model:add( nn.Tanh() )
model:add( nn.Linear(200,10) )
